# Configuration générale
openai:
  model: "gpt-4o"
  temperature: 0

text_splitter:
  chunk_size: 4000
  chunk_overlap: 200

similarity:
  embedding_weight: 0.7
  keyword_weight: 0.3
  threshold: 0.8

celery:
  include:
    - src.adapters.celery.tasks
  config:
    result_expires: 3600
    task_track_started: true

# Configuration CORS
cors:
  allowed_origins:
    - "http://localhost:3000"  # Pour le développement Svelte
    - "http://localhost:5000"  # Pour le serveur de production Svelte
    - "http://localhost:6379"  # Redis
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

# Configuration des types de diagrammes
diagram_types:
  - REQ
  - UC
  - BDD

# Définition des projets avec templates intégrés
projects:
  - name: cdc_1
    label: "CDC_1"
    type: "cdc"
    path: "diagrams/cdc_1/cahier_des_charges.docx"
    file_templates:
      prompt: "diagrams/{project_name}/{diagram_type}.txt"
      output: "diagrams/{project_name}/{diagram_type}_diagram.json"
      entities: "diagrams/{project_name}/{diagram_type}_entities.json"

  - name: crushing_mill
    label: "CRUSHING_MILL"
    type: "part"
    path: "diagrams/crushing_mill/Crushing mill.docx"
    file_templates:
      prompt: "diagrams/{project_name}/{diagram_type}.txt"
      output: "diagrams/{project_name}/{project_name}_{diagram_type}_diagram.json"
      entities: "diagrams/{project_name}/{project_name}_{diagram_type}_entities.json"