# Configuration générale
openai:
  model: "gpt-4o"
  temperature: 0
  api_key: "sk-proj-Qfza5YLxdd9cBnJN9ZGRT3BlbkFJmB1Oaq2KCwobafvbQJnj"

neo4j:
  uri: "bolt://localhost:7687"
  user: "neo4j"
  password: "Password51194"

text_splitter:
  chunk_size: 4000
  chunk_overlap: 200

similarity:
  embedding_weight: 0.7
  keyword_weight: 0.3
  threshold: 0.8

# Configuration des types de diagrammes
diagram_types:
  - REQ
  - UC
  - BDD

# Définition des projets avec templates intégrés
projects:
  - name: cdc_1
    label: "CDC_1"
    type: "cdc"
    path: "diagrams/cdc_1/cahier_des_charges.docx"
    file_templates:
      prompt: "diagrams/{project_name}/{diagram_type}.txt"
      output: "diagrams/{project_name}/{diagram_type}_diagram.md"
      entities: "diagrams/{project_name}/{diagram_type}_entities.json"

  - name: crushing_mill
    label: "CRUSHING_MILL"
    type: "part"
    path: "diagrams/crushing_mill/Crushing mill.docx"
    file_templates:
      prompt: "diagrams/{project_name}/{diagram_type}.txt"
      output: "diagrams/{project_name}/{project_name}_{diagram_type}_diagram.md"
      entities: "diagrams/{project_name}/{project_name}_{diagram_type}_entities.json"