# Test your FastAPI endpoints
GET http://127.0.0.1:8000/
Accept: application/json

###statuts
GET http://127.0.0.1:8000/status
Accept: application/json

### Full project
POST http://127.0.0.1:8000/process/{{project_name}}
Accept: application/json

{
  "project_name": "{{project_name}}"
}
### Project diagramme MD et json
POST http://127.0.0.1:8000/process/{{project_name}}/{{diagram_type}}
Accept: application/json

{
  "project_name": "{{project_name}}",
  "diagram_type": "{{diagram_type}}"
}
### Only json
POST http://127.0.0.1:8000/extract-json/{{project_name}}/{{diagram_type}}

Accept: application/json
{

  "project_name": "{{project_name}}",
  "diagram_type": "{{diagram_type}}"
}

### Neo4j
POST http://127.0.0.1:8000/process-neo4j-data/{{project_name}}/{{diagram_type}}
Content-Type: application/json

{
  "project_name": "{{project_name}}",
  "diagram_type": "{{diagram_type}}"
}
